import Vue from 'vue';
import {
    Pagination,
    Drawer,
    Dialog,
    Menu,
    Submenu,
    MenuItem,
    Input,
    Switch,
    Select,
    Option,
    Button,
    ButtonGroup,
    Table,
    TableColumn,
    Form,
    FormItem,
    Icon,
    Row,
    Col,
    Card,
    Container,
    Header,
    Aside,
    Main,
    Footer,
    Link,
    Image,
    Avatar,
    Dropdown,
    DropdownMenu,
    DropdownItem,
} from 'element-ui';

Vue.use(Pagination);
Vue.use(Dropdown);
Vue.use(DropdownMenu);
Vue.use(DropdownItem);
Vue.use(Avatar);
Vue.use(Drawer);
Vue.use(Dialog);
Vue.use(Menu);
Vue.use(Submenu);
Vue.use(MenuItem);
Vue.use(Input);
Vue.use(Switch);
Vue.use(Select);
Vue.use(Option);
Vue.use(Button);
Vue.use(ButtonGroup);
Vue.use(Table);
Vue.use(TableColumn);
Vue.use(Form);
Vue.use(FormItem);
Vue.use(Icon);
Vue.use(Row);
Vue.use(Col);
Vue.use(Card);
Vue.use(Container);
Vue.use(Header);
Vue.use(Aside);
Vue.use(Main);
Vue.use(Footer);
Vue.use(Link);
Vue.use(Image);

